'use client';
import {ExternalLink, X} from 'lucide-react';
import {useTranslations} from 'next-intl';
import PriceHistoryChart from '@/components/charts/PriceHistoryChart';
import StorePill from '@/components/ui/StorePill';
import type {HistoryRange, Locale, Product} from '@/types/pricewatch';
import {formatPrice, getCombinedHistory, getStoreDelta} from '@/lib/pricewatch/utils';
const ranges: HistoryRange[] = ['7D','30D','90D'];
export default function ProductDrawer({product, open, locale, range, onRangeChange, onClose}: {product: Product | null; open: boolean; locale: Locale; range: HistoryRange; onRangeChange: (range: HistoryRange) => void; onClose: () => void;}) { const t = useTranslations('drawer'); if (!product) return null; return <div className={`pw-drawer ${open ? 'is-open' : ''}`} aria-hidden={!open}><div className="pw-drawer-scrim" onClick={onClose} /><aside className="pw-drawer-panel" role="dialog" aria-modal="true" aria-label={product.name}><header className="pw-drawer-head"><div><p className="pw-eyebrow">{product.brand}</p><h2>{product.name}</h2><span>{product.code}</span></div><button className="pw-icon-button" onClick={onClose} aria-label={t('close')}><X size={18} /></button></header><section className="pw-panel pw-panel-soft"><div className="pw-section-head"><h3>{t('storePrices')}</h3></div><table className="pw-table pw-table-compact"><thead><tr><th>{t('store')}</th><th>{t('current')}</th><th>{t('previous')}</th><th>{t('delta')}</th></tr></thead><tbody>{product.prices.map((entry) => <tr key={entry.store}><td><StorePill store={entry.store} /></td><td>{formatPrice(entry.price, locale)}</td><td>{typeof entry.prevPrice === 'number' ? formatPrice(entry.prevPrice, locale) : '—'}</td><td>{getStoreDelta(entry) > 0 ? '+' : ''}{formatPrice(getStoreDelta(entry), locale)}</td></tr>)}</tbody></table></section><section className="pw-panel pw-panel-soft"><div className="pw-section-head"><h3>{t('history')}</h3><div className="pw-tabs pw-tabs-small">{ranges.map((item) => <button key={item} className={range === item ? 'is-active' : ''} onClick={() => onRangeChange(item)}>{item}</button>)}</div></div><PriceHistoryChart data={getCombinedHistory(product, range)} /></section><section className="pw-panel pw-panel-soft"><div className="pw-section-head"><h3>{t('offers')}</h3></div><div className="pw-list-stack">{product.offers.length ? product.offers.map((offer) => <div key={offer.id} className="pw-offer-item"><div><strong>{offer.title}</strong><span>{offer.details}</span></div><StorePill store={offer.store} /></div>) : <p>{t('noOffers')}</p>}</div></section><a className="pw-link-button" href="https://www.hktvmall.com/" target="_blank" rel="noreferrer noopener">{t('openHktv')} <ExternalLink size={16} /></a></aside></div>; }
