'use client';
import {Star} from 'lucide-react';
import {useTranslations} from 'next-intl';
import Sparkline from '@/components/charts/Sparkline';
import PriceBadge from '@/components/ui/PriceBadge';
import StorePill from '@/components/ui/StorePill';
import TrendChip from '@/components/ui/TrendChip';
import type {Locale, Product} from '@/types/pricewatch';
import {formatPercent, formatPrice, getCombinedHistory, getLowestPrice, getPriceDiff, getSpreadPercent, getTrendDirection} from '@/lib/pricewatch/utils';
export default function ResultsView({products, locale, onOpenProduct, onToggleWatch}: {products: Product[]; locale: Locale; onOpenProduct: (product: Product) => void; onToggleWatch: (id: string) => void;}) { const t = useTranslations('results'); return <section className="pw-panel"><div className="pw-section-head"><div><p className="pw-eyebrow">{t('eyebrow')}</p><h2>{t('title')}</h2></div></div><div className="pw-table-wrap"><table className="pw-table"><thead><tr><th>{t('columns.product')}</th><th>{t('columns.category')}</th><th>{t('columns.cheapest')}</th><th>{t('columns.spread')}</th><th>{t('columns.history')}</th><th>{t('columns.trend')}</th><th>{t('columns.offer')}</th><th>{t('columns.watch')}</th></tr></thead><tbody>{products.map((product) => { const lowest = getLowestPrice(product); const direction = getTrendDirection(product); return <tr key={product.id} onClick={() => onOpenProduct(product)}><td><div className="pw-product-cell"><strong>{product.name}</strong><span>{product.brand}</span></div></td><td>{product.category}</td><td>{lowest ? <div className="pw-cheapest-cell"><StorePill store={lowest.store} /><strong>{formatPrice(lowest.price, locale)}</strong></div> : '—'}</td><td>{formatPrice(getPriceDiff(product), locale)} · {formatPercent(getSpreadPercent(product), locale)}</td><td><Sparkline data={getCombinedHistory(product, '30D')} /></td><td><TrendChip direction={direction} value={formatPercent(getSpreadPercent(product), locale)} /></td><td>{product.offers.length ? <PriceBadge label={t('offerCount', {count: product.offers.length})} tone="warning" /> : <PriceBadge label={t('none')} />}</td><td><button className="pw-star-button" onClick={(event) => { event.stopPropagation(); onToggleWatch(product.id); }} aria-label={t('watch')}><Star size={16} fill={product.watched ? 'currentColor' : 'none'} /></button></td></tr>; })}</tbody></table></div></section>; }
